[package]
name = "interchain_queries"
version = "0.1.0"
authors = ["cosmos-team <cosmos-team@p2p.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "1.0.0", features=["iterator", "stargate"] }
schemars = "0.8.10"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
protobuf = { version = "3", features = ["with-bytes"] }

