[package]
name = "neutron_sudo"
version = "0.1.0"
edition = "2021"
authors = ["cosmos-team <cosmos-team@p2p.org>"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[dependencies]
cosmwasm-std = { version = "1.0.0", features = ["staking"] }
cosmos-sdk-proto = { version = "0.12.2", default-features = false }
prost = "0.10"
cw-storage-plus = { version = "0.13.2", features = ["iterator"]}
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
schemars = "0.8.10"
